add single backend
dataloop-ai-apps/dataset-insights pull request #7
Opened 2024-12-26 14:59 UTC by ludoHorv

2025-01-06 16:21 UTC, ShadiMah requested changes

2025-01-06 16:21 UTC, ShadiMah commented on app.py
Add enum instead of hardcoded strings

2025-01-06 20:19 UTC, ludoHorv commented on app.py
> +                    .get('system', {})
so the string is not long, comming from formatter

2025-01-07 09:30 UTC, ShadiMah commented on exporter.py
> +class BuildStatus(Enum):
Inheritance (str, Enum) then you don't need .value

2025-01-07 09:30 UTC, ShadiMah requested changes

2025-01-07 09:30 UTC, ShadiMah commented on exporter.py
> +    ready = "ready"
Enum attributes capital

2025-01-07 09:42 UTC, LudoHor commented on exporter.py
> +class BuildStatus(Enum):
done

2025-01-07 10:02 UTC, ShadiMah approved these changes

2025-01-07 10:14 UTC, merged